name: deploy website
on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.GITHUB }}
          now-args: '--prod' #Optional
          now-org-id: 'example_org_id' #Required
          now-project-id: 'example_project_id' #Required
          working-directory: ./
