name: deploy website
on: [merge_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.GITHUB }}
          now-args: '--prod'
          now-org-id: ${{ secrets.orgId }}
          now-project-id: ${{ secrets.projectId }}
          working-directory: ./
