name: deploy website
on:
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.GITHUB }}
          now-org-id: ${{ secrets.orgId }}
          now-project-id: ${{ secrets.projectId }}
          working-directory: ./
